vm:
  name: "win10"
  vcpus: 4
  memory: 16384
  os_variant: "win10"
  #efi or legacy
  bios: "efi"
  #required for bios efi
  secureboot: True
  #3d, spice, vnc, serial_console
  graphics: "spice"
  #usbver: "2"

cdroms:
  drivercdrom:
    uri: "/ramdisk/win.driveriso.raw"
    readonly: True
    isofile: "/var/lib/libvirt/images/virtio-win-0.1.266.iso"

  #installcdrom:
  #  uri: "/ramdisk/win10.installiso.raw"
  #  readonly: True
  #  isofile: "/var/lib/libvirt/images/Win10_22H2_English_x64v1.iso"

  #unattendcrom:
  #  uri: "/ramdisk/win.unattendiso.raw"
  #  readonly: True
  #  isofile: "/var/lib/libvirt/images/win10-unattend.iso"


disks:
  osdisk:
    uri: "/ramdisk/win10.osdisk.raw"
    bus: "scsi"
    format: "raw"
    # size in GiB
    size: 60

  installdisk:
    uri: "/ramdisk/win10.install.raw"
    bus: "usb"
    format: "raw"
    readonly: True
    removable: True
    # size in GiB, optional if converted from image file
    #size: 2
    imgfile: "/var/lib/libvirt/images/Win10_22H2_English_x64v1.img"
    insha256sum: "<a sha256sum>"
    imgformat: "raw"

  #dummyvirtiodisk:
  #  uri: "/ramdisk/win10.dummyvirtiodisk.qcow2"
  #  bus: "virtio"
  #  format: "qcow2"
  #  size: 1

  #dummyvirtioscsidisk:
  #  uri: "/ramdisk/win10.dummyvirtioscsidisk.qcow2"
  #  bus: "scsi"
  #  format: "qcow2"
  #  size: 1

  #driverdisk:
  #  uri: "/ramdisk/win.driver.raw"
  #  bus: "usb"
  #  format: "raw"
  #  readonly: True
  #  removable: True
  #  # size in GiB, optional if converted from image file
  #  #size: 2
  #  imgfile: "/var/lib/libvirt/images/virtio-win-0.1.266.iso"
  #  imgformat: "raw"

  answerdisk:
    uri: "/ramdisk/win.answer.raw"
    bus: "usb"
    format: "raw"
    readonly: True
    removable: True
    # size in GiB, optional if converted from image file
    #size: 2
    imgfile: "/var/lib/libvirt/images/autounattend.img"
    imgformat: "raw"

network:
  #model: "e1000e"
  # nat, isolated, bridge, macvtap, ipvtap
  type: "isolated"
  mac: "52:54:00:dd:a1:0a"
  #required when backing interface is needed: bridge, macvtap, ipvtap
  parent_interface: "enp58s0u1u3u3"

