vm:
  name: "win10"
  vcpus: 4
  memory: 16384
  os_variant: "win10"
  #efi or legacy
  bios: "efi"
  #required for bios efi
  secureboot: True
  #3d, spice, vnc, serial_console
  graphics: "3d"
  #usbver: "2"

ramdisk:
  path: "/ramdisk"
  # size in GiB
  size: 30

disks:
  osdisk:
    uri: "/ramdisk/win10.osdisk.raw"
    bus: "sata"
    format: "raw"
    # size in GiB
    size: 20

  installdisk:
    uri: "/ramdisk/win10.install.raw"
    bus: "usb"
    format: "raw"
    readonly: True
    removable: True
    # size in GiB, optional if converted from image file
    #size: 2
    imgfile: "/var/lib/libvirt/images/win10.img"
    imgformat: "raw"


  answerdisk:
    uri: "/ramdisk/win10.answer.raw"
    bus: "usb"
    format: "raw"
    readonly: True
    removable: True
    # size in GiB, optional if converted from image file
    #size: 2
    imgfile: "/var/lib/libvirt/images/autounattend.img"
    imgformat: "raw"

network:
  #model: "e1000e"
  # default, isolated, bridge, macvtap, ipvtap
  type: "isolated"
  mac: "52:54:00:dd:a1:0a"
  #required when backing interface is needed: bridge, macvtap, ipvtap
  parent_interface: "enp58s0u1u3u3"

